# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tommaso Turchi
name: Tommaso Turchi
position: Researcher | Coder
email: hi@tommasoturchi.com
description: >-
  I am a researcher in human-machine interaction and human-centred artificial intelligence. I am currently an assistant professor at the [University of Pisa](https://www.unipi.it/).

  I received my Ph.D. from [Brunel University London](https://brunel.ac.uk/) in 2019 where I was advised by
  [Alessio Malizia](https://alessiomalizia.wordpress.com/) and
  [David Bell](https://www.brunel.ac.uk/people/david-bell).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tommasoturchi.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tommasoturchi
github_username: tommasoturchi
google_scholar: llEMIRUAAAAJ

# Build settings
theme: minima
whitelist: [jekyll-analytics]
plugins:
  - jekyll-feed
  - jekyll-analytics

sass:
  style: compact
  quiet_deps: true

jekyll_analytics:
  Plausible:
    domain: 'tommasoturchi.com'   # The domain configured in plausible
    source: 'https://plausible.io/js/script.js' # The source of the javascript

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
